### ISSUE TITLE
maven-jar-plugin build warnings when building remora-core

### ISSUE THREAD

**Issue by mjok** [Nastel/remoraj#12]
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.jkoolcloud.remora:remora-core:jar:0.1.9-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-jar-plugin @ line 135, column 25
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[

**Comment by amavashev** [comment]
Checked in fix, please verify

**Comment by mjok** [comment]
Ok. It seems all right. Close
