### ISSUE TITLE
Ability to set application name when running remora agent

### ISSUE THREAD

**Issue by mjok** [Nastel/remoraj#13]
Update streams configuration to set vmid as application name if one does not exist

Scott:
One of the things that I'd like to see in the RemoraJ streamed data is the "ApplName", but I'm not seeing any content in that field ... see attached Excel doc, downloaded from an XRay viewlet ... 

This actually explains why when I look at my demo data streamed from the RemoraJ chronicle queue to jKool via tnt4j-streams, I always feel like there is something missing ... there's actually nothing in the data that goes to Xray that allows me to identify the actual applications ... but I can see the class names and method names in the chronicle queue file 20200617-20.cq4 ... so there must be a way to get that information to XRay via tnt4jstreams. 

Marius
for applName  we set it on application server as actual application; so if it's a standalone application we don't set it. There is "vmid" you could use. I think that it's a good point, I will update streams configuration to default set applName to vmid this case the standalone applications's would have applName. By default "vmid" is the process name, still that could be not very usable, it will change everytime you restart the application, you can override this by specifying "remora.vmid" java option (-D).

**Comment by amavashev** [comment]
I suggest to use a separate property to handle app names. Example: remoraj.appl.name=MyApp
vm.id is identify a java container (app server) vs app name.
