### ISSUE TITLE
unable to get the IBM websphere console after changing the server.xml file

### ISSUE THREAD

**Issue by vaishali3026** [Nastel/remoraj#3]
[native_stderr.log](https://github.com/Nastel/remoraj/files/4552273/native_stderr.log)
configure the was server after that change the server.xml file.for setting the generic jvm path.after that restart the was server. not getting the ibm console. attached the logs.

**Comment by kausandr** [comment]
Remora is built for Java 8, so any try to use on Java7 or Java6 will fail.

Set your WAS to use Java8.

**Comment by rnikula** [comment]
note that some versions of WAS are only certified for specific versions of Java.   We have to verify which versions we will support (remember, you had to redo the stream jmx to support it for same reason).

**Comment by kausandr** [comment]
Since all WASs <=8.5 (and running on Java6) already reached End-Of-Life, supported WASs are >=8.5.5 (running Java8).

**Comment by vaishali3026** [comment]
updated the WAS server to 8.5.5.17. issue got resolved.
