### ISSUE TITLE
Agent doesn't work with OpenJDK 14

### ISSUE THREAD

**Issue by 3alster** [Nastel/remoraj#4]
When trying to start an app with remora agent got an error during startup 

> Running RemoraJ 0.1.7-2020-05-08T07:17:08Z
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-apacheHttpClient-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-bank_benchmark-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-control-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-ejb3-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-httpUrlConnection-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-javaxServlet-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-jboss-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-jdbc-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-jms-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-kafka-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-simple-test-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-spring-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-weblogic-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-websocket-0.1.7.jar
Found: file:/C:/_dev/pflbRemoraJ/remora-0.1.7/modules/remora-websphere-0.1.7.jar
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
Will ignore classes com.ibm.wsspi
Will ignore classes org.eclipse
Will ignore classes com.ibm.ws
Will ignore classes com.ibm.websphere.models
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes com.ibm.ws.webcontainer.spiadapter.collaborator
Will ignore classes com.ibm.ws.injectionengine
Will ignore classes com.ibm.ws.webcontainer.spiadapter
Will ignore classes com.ibm.msg.client.commonservices
Will ignore classes org.osgi
Will ignore classes com.ibm.wsspi.bootstrap.osgi
Will ignore classes com.ibm.ws.runtime.component
Will ignore classes weblogic.jdbc
Will ignore classes org.osgi
Will ignore classes org.glassfish.enterprise
Will ignore classes org.jboss.as.security
Will ignore classes org.apache.cxf
Will ignore classes org.apache.neethi
Will ignore classes org.apache.yoko
Will ignore classes org.takes
Will ignore classes org.cactoos
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.openhft.chronicle.core.Jvm to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of net.openhft.chronicle.core.Jvm
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.AssertionError: java.lang.NoSuchMethodException: sun.nio.ch.FileChannelImpl.map0(int,long,long)
        at net.openhft.chronicle.core.Jvm.getMethod0(Jvm.java:395)
        at net.openhft.chronicle.core.Jvm.getMethod(Jvm.java:374)
        at net.openhft.chronicle.core.OS.lambda$static$0(OS.java:51)
        at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:53)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208)
        at java.base/java.lang.ClassValue.get(ClassValue.java:114)
        at net.openhft.chronicle.core.OS.map0(OS.java:354)
        at net.openhft.chronicle.core.OS.map(OS.java:333)
        at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:348)
        at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:296)
        at net.openhft.chronicle.bytes.MappedBytes.acquireNextByteStore0(MappedBytes.java:374)
        at net.openhft.chronicle.bytes.MappedBytes.readVolatileInt(MappedBytes.java:694)
        at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.build(SingleTableBuilder.java:100)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata(SingleChronicleQueueBuilder.java:431)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.preBuild(SingleChronicleQueueBuilder.java:996)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:329)
        at com.jkoolcloud.remora.core.output.ChronicleOutput.init(ChronicleOutput.java:114)
        at com.jkoolcloud.remora.core.output.OutputManager.install(OutputManager.java:64)
        at com.jkoolcloud.remora.core.output.OutputManager.<init>(OutputManager.java:40)
        at com.jkoolcloud.remora.core.output.OutputManager.<clinit>(OutputManager.java:29)
        at com.jkoolcloud.remora.Remora.premain(Remora.java:86)
        ... 6 more
Caused by: java.lang.NoSuchMethodException: sun.nio.ch.FileChannelImpl.map0(int,long,long)
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2553)
        at net.openhft.chronicle.core.Jvm.getMethod0(Jvm.java:379)
        ... 27 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
errorlevel=1
Press any key to continue . . .

**Comment by amavashev** [comment]
Seems like method: sun.nio.ch.FileChannelImpl.map0(int,long,long) is not found. Will need to be investigated. Try to override output to Sysout instead of a memory mapped queue (see details https://github.com/Nastel/remoraj#agent-trace-output)

**Comment by amavashev** [comment]
Bug in a Chronicle Queue dependency: https://github.com/OpenHFT/Chronicle-Queue/issues/652. RemoraJ needs to be updated to the latest version.

**Comment by mjok** [comment]
I have updated the snapshot version, as well fixed the version 0.1.7, and updated the binaries of the release. You could get these there: https://github.com/Nastel/remoraj/releases/tag/0.1.7

**Comment by amavashev** [comment]
@3alster  please let us know if the latest posted 0.1.7 fixes the problem.

**Comment by amavashev** [comment]
Issue should be resolved with updated dependencies
